<?php

use Drupal\node\Entity\NodeType;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_entity_extra_field_info().
 */
function dwell_extrafields_entity_extra_field_info()
{

  $extra = [];

  foreach (NodeType::loadMultiple() as $bundle) {

    $extra['node'][$bundle->id()]['display']['title_field'] = [
      'label' => t('Title'),
      'description' => t('Title field'),
      'weight' => 100,
      'visible' => false,
    ];
  }

  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function dwell_extrafields_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode)
{

  $title = $entity->getTitle();

  if ($display->getComponent('title_field')) {

    $build['title_field'] = [
      '#type' => 'inline_template',
      '#template' => '<h1 class="page-title">{{ title }}</h1>',
      '#context' => [
        'title' => $title,
      ],
    ];
  }
}
